root: true
extends: airbnb
rules:
  comma-dangle:
    - error
    - objects: only-multiline
  max-len: off
  no-console: off
  no-else-return: off
  no-nested-ternary: off
  no-return-assign: off
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  no-unexpected-multiline: error
  semi:
    - error
    - never
plugins:
  - import
env:
  es6: true
  node: true
  mocha: true
